"""``DreamerV4`` — top-level assembly: tokenizer + world model + action expert.

Wires the three subsystems into one ``nn.Module`` and exposes:

- ``step`` — the ``Policy`` protocol used for real-env collection: encode the obs
  to latent tokens, act with the (engine-masked) action expert. Also returns the
  latents ``z`` so collectors can maintain a ``WorldModelMemory`` context window
  without re-encoding.
- ``imagine`` — autoregressive shortcut-denoised rollout. Seeded either from a
  single frame or from a **context window** of replay latents + their actions
  (proper Dreamer 4 usage: the transformer world model *is* the memory, so
  imagination should start with history, not a lone frame). Each new frame is
  generated by ``WorldModel.sample_next`` (Euler shortcut denoising); actions come
  from the current actor under the tokenizer's *predicted* action mask; rewards /
  continues are read from one clean pass over the full imagined sequence
  (arrive-aligned). Returns detached tensors.
- ``open_loop`` — teacher-forced generation for dynamics analysis: real actions,
  model-generated latents; compare against the encoder's real latents.
- ``build_optimizers`` — world (tokenizer + world model) / actor / critic, with
  per-module freezing from ``cfg.freeze``: frozen params get
  ``requires_grad_(False)`` and fully-frozen groups are omitted (the trainer
  skips the corresponding update), enabling pretrain-then-RL runs.
"""

from __future__ import annotations

import torch
import torch.nn as nn
from tensordict import TensorDict

from core.registry import register

from .config import DreamerV4Config
from .tokenizer import GridTokenizer
from .world_model import WorldModel, _MRTS_OBS_CHANNELS, opponent_source_cells
from .action_expert import ActionExpert


class DreamerV4(nn.Module):
    def __init__(self, obs_shape, action_nvec, cfg: DreamerV4Config | None = None,
                 device: str = "cpu") -> None:
        super().__init__()
        self.cfg = cfg or DreamerV4Config()
        if not torch.is_tensor(action_nvec):
            action_nvec = torch.as_tensor(list(action_nvec), dtype=torch.long)
        self.action_nvec = action_nvec
        self.grid_cells = int(action_nvec[0])
        self.n_comp = len(action_nvec) - 1
        mask_width = 1 + int(action_nvec[1:].sum())

        _, h, w = obs_shape
        self.tokenizer = GridTokenizer(obs_shape, self.cfg.tokenizer, mask_width=mask_width)
        n_spatial, d_latent = self.tokenizer.n_spatial, self.tokenizer.d_latent
        self.world_model = WorldModel(n_spatial, d_latent, action_nvec[1:], (h, w),
                                      self.cfg.dynamics)
        self.action_expert = ActionExpert(
            obs_shape, action_nvec, n_spatial, d_latent, self.cfg.actor_critic
        )
        self._apply_freeze()

        self.device = device
        self.to(device)

    # --- freezing ---------------------------------------------------------
    def _apply_freeze(self) -> None:
        fz = self.cfg.freeze
        self.tokenizer.requires_grad_(not fz.tokenizer)
        self.world_model.requires_grad_(not fz.world_model)
        for m in (self.action_expert.decoder, self.action_expert.action_conv):
            m.requires_grad_(not fz.actor)
        self.action_expert.critic.requires_grad_(not fz.critic)
        # The EMA target is never optimized, frozen or not.
        self.action_expert.target_critic.requires_grad_(False)

    # --- Policy protocol (real-env collection) ---------------------------
    @torch.no_grad()
    def step(self, obs: torch.Tensor, mask: torch.Tensor | None = None,
             deterministic: bool = False) -> TensorDict:
        obs = obs.to(self.device)
        mask = mask.to(self.device) if mask is not None else None
        z = self.tokenizer.encode(obs)                       # (N, n_spatial, d_latent)
        action, logprob, _, value = self.action_expert.act(z, mask, deterministic=deterministic)
        return TensorDict(
            {"action": action, "logprob": logprob, "value": value, "z": z},
            batch_size=[obs.shape[0]],
        )

    # --- imagination -----------------------------------------------------
    def _empty_actions(self, B: int, T: int, device) -> torch.Tensor:
        return torch.zeros(B, T, self.grid_cells, self.n_comp, dtype=torch.long, device=device)

    @torch.no_grad()
    def imagine(self, z0: torch.Tensor, horizon: int | None = None,
                ctx_action: torch.Tensor | None = None,
                ctx_is_first: torch.Tensor | None = None,
                ctx_opponent_action: torch.Tensor | None = None,
                opponent_policy=None, use_opp_head: bool = True) -> dict:
        """Imagined rollout from ``z0``: (B,n_spatial,d_latent) single frame, or
        (B,Tc,n_spatial,d_latent) replay context with ``ctx_action`` (B,Tc,H*W,7)
        the actions chosen at those frames (the last one is re-chosen by the
        actor) and ``ctx_is_first`` (B,Tc) episode-start flags.

        Joint-action world model: ``ctx_opponent_action`` (B,Tc,H*W,7) are the
        recorded opponent actions of the context frames. During the imagined
        steps the opponent is, in order of preference: played by
        ``opponent_policy`` (two-sided dreams: any ``step(z, mask) ->
        {"action": ...}``-style callable acting on the shared latent state,
        e.g. a frozen league snapshot's action expert); sampled from the world
        model's opponent-policy head when the model has one and ``use_opp_head``
        (v4.4 — an explicit BC opponent instead of the averaged marginal,
        MBOM level-0; costs one extra clean trunk pass per imagined step); or
        marked unknown so the model falls back to its learned marginal
        (``unknown_opp``).

        Returns detached: ``z`` (B,H+1,...), ``action`` (B,H,H*W,7), ``mask``
        (B,H,H*W,mask_width), ``reward`` (B,H), ``cont`` (B,H)."""
        horizon = horizon or self.cfg.actor_critic.imagine_horizon
        flow_steps = self.cfg.actor_critic.imagine_flow_steps
        if z0.dim() == 3:
            z0 = z0[:, None]
        B, Tc = z0.shape[:2]
        device = z0.device
        if ctx_action is None:
            assert Tc == 1, "context windows longer than 1 need ctx_action"
            ctx_action = self._empty_actions(B, Tc, device)
        else:
            ctx_action = ctx_action.long().clone()
        if ctx_is_first is None:
            ctx_is_first = torch.zeros(B, Tc, dtype=torch.bool, device=device)
        else:
            ctx_is_first = ctx_is_first.bool().clone()
        if ctx_opponent_action is None:
            opp_seq = self._empty_actions(B, Tc, device)
            unk_seq = torch.ones(B, Tc, dtype=torch.bool, device=device)
        else:
            opp_seq = ctx_opponent_action.long().clone()
            unk_seq = torch.zeros(B, Tc, dtype=torch.bool, device=device)

        z_seq = z0
        act_seq = ctx_action
        first_seq = ctx_is_first
        a_list, m_list = [], []
        for _ in range(horizon):
            z_t = z_seq[:, -1]
            mask = (torch.sigmoid(self.tokenizer.decode_mask(z_t)) > 0.5).float()
            action, _, _, _ = self.action_expert.act(z_t, mask)
            a_list.append(action)
            m_list.append(mask)
            act_seq = act_seq.clone()
            act_seq[:, -1] = action                          # chosen at the last frame
            if opponent_policy is not None:
                # Two-sided dream: the opponent picks simultaneously on the shared
                # latent (the predicted mask is learner-perspective — a snapshot
                # opponent should tolerate or ignore it).
                opp_seq = opp_seq.clone()
                opp_seq[:, -1] = opponent_policy(z_t, mask)
                unk_seq = unk_seq.clone()
                unk_seq[:, -1] = False
            elif use_opp_head and self.world_model.opp_head is not None:
                # Predicted opponent (v4.4): sample the frame's opponent action
                # from the BC head on a clean trunk pass. Simultaneous-move safe:
                # slot -1's trunk features only see actions < t (the shift), so
                # the just-chosen actor action cannot leak into the opponent.
                h_t = self.world_model.contextualize(
                    z_seq, act_seq, first_seq,
                    opponent_action=opp_seq, opp_unknown=unk_seq)["h"][:, -1]
                src = opponent_source_cells(self.tokenizer.decode(z_t)) \
                    if self.tokenizer.obs_channels == _MRTS_OBS_CHANNELS else None
                opp_seq = opp_seq.clone()
                opp_seq[:, -1] = self.world_model.sample_opponent(h_t, src)
                unk_seq = unk_seq.clone()
                unk_seq[:, -1] = False
            z_next = self.world_model.sample_next(
                z_seq, act_seq, first_seq, flow_steps,
                opponent_action=opp_seq, opp_unknown=unk_seq)
            if self.cfg.tokenizer.tanh_bottleneck:
                z_next = z_next.clamp(-1.0, 1.0)
            z_seq = torch.cat([z_seq, z_next[:, None]], dim=1)
            act_seq = torch.cat([act_seq, self._empty_actions(B, 1, device)], dim=1)
            opp_seq = torch.cat([opp_seq, self._empty_actions(B, 1, device)], dim=1)
            unk_seq = torch.cat(
                [unk_seq, torch.ones(B, 1, dtype=torch.bool, device=device)], dim=1)
            first_seq = torch.cat(
                [first_seq, torch.zeros(B, 1, dtype=torch.bool, device=device)], dim=1)

        # One clean pass over the whole sequence: reward/continue at slot t are the
        # scalars of the t-1 -> t transition, so imagined step i reads slot Tc+i.
        ctx = self.world_model.contextualize(z_seq, act_seq, first_seq,
                                             opponent_action=opp_seq,
                                             opp_unknown=unk_seq)
        return {
            "z": z_seq[:, Tc - 1:],
            "action": torch.stack(a_list, dim=1),
            "mask": torch.stack(m_list, dim=1),
            "reward": ctx["reward"][:, Tc:],
            "cont": torch.sigmoid(ctx["continue_logit"][:, Tc:]),
        }

    @torch.no_grad()
    def open_loop(self, z: torch.Tensor, action: torch.Tensor,
                  is_first: torch.Tensor | None = None, context: int = 4,
                  flow_steps: int | None = None,
                  opponent_action: torch.Tensor | None = None) -> torch.Tensor:
        """Teacher-forced dynamics analysis: keep the real actions, generate the
        latents for slots ``context..T-1`` from the first ``context`` real frames.
        ``opponent_action`` (B,T,H*W,7) supplies the recorded opponent stream
        (None = opponent unknown, the marginal model). Returns predicted latents
        (B, T-context, n_spatial, d_latent) to compare against the encoder's
        ``z[:, context:]``."""
        flow_steps = flow_steps or self.cfg.actor_critic.imagine_flow_steps
        B, T = z.shape[:2]
        assert 0 < context < T, "need at least one context frame and one target"
        if is_first is None:
            is_first = torch.zeros(B, T, dtype=torch.bool, device=z.device)
        z_seq = z[:, :context]
        for t in range(context, T):
            opp = opponent_action[:, :t] if opponent_action is not None else None
            z_next = self.world_model.sample_next(
                z_seq, action[:, :t], is_first[:, :t], flow_steps,
                opponent_action=opp)
            if self.cfg.tokenizer.tanh_bottleneck:
                z_next = z_next.clamp(-1.0, 1.0)
            z_seq = torch.cat([z_seq, z_next[:, None]], dim=1)
        return z_seq[:, context:]

    # --- multi-optimizer (freeze-aware) -----------------------------------
    def build_optimizers(self) -> dict[str, torch.optim.Optimizer]:
        self._apply_freeze()

        def trainable(*modules):
            return [p for m in modules for p in m.parameters() if p.requires_grad]

        c = self.cfg
        groups = {
            "world": (trainable(self.tokenizer, self.world_model), c.world_lr),
            "actor": (trainable(self.action_expert.decoder,
                                self.action_expert.action_conv), c.actor_lr),
            "critic": (trainable(self.action_expert.critic), c.critic_lr),
        }
        return {name: torch.optim.Adam(params, lr=lr, eps=1e-5)
                for name, (params, lr) in groups.items() if params}


@register("model", "dreamerv4")
def build_dreamerv4(obs_shape, action_nvec, device="cpu", **kwargs) -> DreamerV4:
    cfg = DreamerV4Config.from_dict(kwargs)
    return DreamerV4(obs_shape, action_nvec, cfg=cfg, device=device)
